Repository mozilla/bigquery-etl, pull requests merged in 2022-01, with the labels that each got.

#2641 bug: explicitly casting dates in where clause to date
  sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/query.sql
Labels: bug

#2480 Added JDK install to python-deps stage for pyjnius build on M1
  .circleci/config.yml
  Dockerfile
Labels: enhancement

#2670 modified regrets reporter summary query to run query against all data
  dags/bqetl_regrets_reporter_summary.py
  sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/init.sql
  sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/query.sql
Labels: bug

#2655 tweaked comment in validate-dags to mention that tags are also validated
  .circleci/config.yml
Labels: docs
