Repository mozilla/bigquery-etl, pull requests merged in 2023-05, with the labels that each got.

#3712 feat(DENG-788): adding firefox_ios.attributable_clients table
  dags/bqetl_analytics_tables.py
  dags/bqetl_org_mozilla_firefox_derived.py
  sql/moz-fx-data-shared-prod/firefox_ios/attributable_clients/view.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/init.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/query.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/schema.yaml
Labels: feature

#3788 bug(DENG-788): adding first_seen_date to schema.yaml to match with the query.sql file
  sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/schema.yaml
Labels: bug

#3811 feat(DENG-789): added authorized views for accessing apple_ads datasets
  sql/moz-fx-data-shared-prod/apple_ads/ad_group_report/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads/ad_group_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/campaign_report/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads/campaign_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/dataset_metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads/keyword_report/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads/keyword_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/organization_report/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads/organization_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/search_term_report/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads/search_term_report/view.sql
Labels: enhancement

#3812 feat(DENG-789): added apple_ads namespace views to dryrun skip
  bigquery_etl/dryrun.py
Labels: bug

#3819 Update grpcio to a version that provides darwin arm64 builds
  bqetl
  requirements.txt
Labels: dependencies

#3847 feat(DENG-789): making apple ads data accessible
  bigquery_etl/dryrun.py
  dags.yaml
  dags/bqetl_fivetran_apple_ads.py
  sql/moz-fx-data-shared-prod/apple_ads/ad_group_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/campaign_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/keyword_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/organization_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads/search_term_report/view.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/ad_group_report_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/ad_group_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/ad_group_report_v1/schema.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/campaign_report_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/campaign_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/campaign_report_v1/schema.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/dataset_metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/keyword_report_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/keyword_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/keyword_report_v1/schema.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/organization_report_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/organization_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/organization_report_v1/schema.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/search_term_report_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/apple_ads_external/search_term_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/search_term_report_v1/schema.yaml
Labels: enhancement

#3870 feat(DENG-980): fxa_users_services_first_seen view updated to use v2
  sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_first_seen/view.sql
Labels: enhancement
