Repository mozilla/bigquery-etl, pull requests merged in 2024-01, with the labels that each got.

#4707 Bug 1868850 - Remove failing warn checks from UM
  sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql
Labels: bug, data checks

#4812 # bug(): wrapping commented out test in jinja comment to exclude it from the final output
  sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql
Labels: bug

#4830 feat(DENG-2083): updated the source of is_activated inside the firefox_ios_clients view
  sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/schema.yaml
Labels: bug

#4833 feat(DENG-1776): added fenix client funnels to shredder config
  bigquery_etl/shredder/config.py
Labels: enhancement

#4852 feat(DENG-2086): added firefox_ios_derived.firefox_ios_clients_v1 to shredder config
  bigquery_etl/shredder/config.py
Labels: enhancement

#4853 feat(DENG-2432): removed activations field from firefox_ios_clients_v1
  sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/init.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/query.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/schema.yaml
Labels: enhancement

#4854 feat(DENG-2432/): irefox ios clients v1 removing activation field view update
  sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql
Labels: bug

#4831 feat(DENG-1697): Descheduled all FxA queries using the old AWS based tables
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_auth_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_content_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_device_command_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_stdout_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_auth_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_content_events_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_stdout_events_v1/metadata.yaml
Labels: deprecation

#4851 feat(DENG-1590): added existing fxa tables to shredder config
  bigquery_etl/shredder/config.py
Labels: enhancement

#4910 bug(1876789): Delete active_users_aggregates_v1/checks.sql as no longer needed due to the dataset deprecation
  sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/checks.sql
Labels: deprecation

#4908 bug(): remove unwanted space in bqetl checks labels
  sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/checks.sql
  sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/checks.sql
  sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.checks.sql
Labels: bug
