Repository mozilla/bigquery-etl, pull requests merged in 2025-07, with the labels that each got.

#7746 feat(DENG-8914): update mobile_view templates inside active_users_aggregates generators so that focus products use composite dataset
  bigquery_etl/metadata/validate_metadata.py
  sql_generators/active_users_aggregates_v3/templates/mobile_view.sql
  sql_generators/active_users_aggregates_v4/templates/mobile_view.sql
  sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
  sql_generators/usage_reporting/usage_reporting.py
  tests/cli/test_cli_metadata.py
  tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/fenix/usage_reporting_active_users/view.sql
  tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_desktop/usage_reporting_active_users/view.sql
  tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_ios/usage_reporting_active_users/view.sql
Labels: enhancement

#7757 DENG-9093 Pull Dashboard Service data from BigEye API and upload to BigQuery
  bqetl_project.yaml
  dags.yaml
  sql/moz-fx-data-shared-prod/bigeye_derived/dashboard_service_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/bigeye_derived/dashboard_service_v1/query.py
  sql/moz-fx-data-shared-prod/bigeye_derived/dashboard_service_v1/schema.yaml
Labels: enhancement, feature

#7835 fix: correct new_profile_activations and activation_clients expected test results
  tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_clients_v1/bigconfig.yml
  tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/fenix_derived/new_profile_activations_v1/bigconfig.yml
  tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_clients_v1/bigconfig.yml
  tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activations_v1/bigconfig.yml
Labels: bug

#7857 fix: undeprecate clients_activation_v1 as still in use
  sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/metadata.yaml
Labels: bug

#7856 chore: delete ads.fakespot_daily_events_rollup view definition as it is pointing to bq asset that no longer exists
  sql/moz-fx-data-shared-prod/ads/fakespot_daily_events_rollup/metadata.yaml
  sql/moz-fx-data-shared-prod/ads/fakespot_daily_events_rollup/view.sql
Labels: bug, deprecation
