Repository mozilla/bigquery-etl, pull requests merged in 2025-08, with the labels that each got.

#7862 add composite_key_uniqueness_3_column to the list of saved metrics in sql/bigconfig.yml
  sql/bigconfig.yml
Labels: data checks

#7953 feat(DENG-9250): add syndicate dataset for firefox_app_store_v2
  sql/moz-fx-data-shared-prod/app_store_v2_syndicate/dataset_metadata.yaml
Labels: enhancement

#8016 feat(DENG-8022): update new_downloads and redownloads and total_downloads field references to use the new tap_ prefix
  sql/moz-fx-data-shared-prod/apple_ads_external/ad_group_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/campaign_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/keyword_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/organization_report_v1/query.sql
  sql/moz-fx-data-shared-prod/apple_ads_external/search_term_report_v1/query.sql
Labels: migration

#8028 completing backfill
  sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_component_content_v1/backfill.yaml
Labels: backfill
