Repository mozilla/bigquery-etl, pull requests merged in 2025-02, with the labels that each got.

#6963 fix: revert the friendly name change for fenix and create a new field instead of joining with the search dataset
  sql_generators/mobile_kpi_support_metrics/__init__.py
  sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.query.sql
Labels: bug

#6960 feat: add os and os_version to retention_clients and engagement_clients
  sql_generators/mobile_kpi_support_metrics/templates/engagement_clients.view.sql
  sql_generators/mobile_kpi_support_metrics/templates/retention_clients.view.sql
Labels: enhancement

#6965 fix: set submission_date as the partition field
  sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.metadata.yaml
Labels: bug

#6943 feat: add backfill entry for mobile products for new_profile_activations
  sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/focus_android_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/focus_ios_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/klar_android_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/klar_ios_derived/new_profile_activations_v1/backfill.yaml
Labels: backfill

#6977 fix(bug-1946076): handle the case of is_default_browser existing in both baseline and metrics now
  sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql
Labels: bug

#6979 feat(DENG-7805): move new_profile_activations_v1 backfill entry to Complete
  sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/focus_android_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/focus_ios_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/klar_android_derived/new_profile_activations_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/klar_ios_derived/new_profile_activations_v1/backfill.yaml
Labels: backfill

#6991 feat: add backfill entries for new_profile_metrics_marketing_geo_testing_v1
  sql/moz-fx-data-shared-prod/fenix_derived/new_profile_metrics_marketing_geo_testing_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_metrics_marketing_geo_testing_v1/backfill.yaml
Labels: backfill

#6994 feat: move new_profile_metrics_marketing_geo_testing_v1 backfills to Complete
  sql/moz-fx-data-shared-prod/fenix_derived/new_profile_metrics_marketing_geo_testing_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_metrics_marketing_geo_testing_v1/backfill.yaml
Labels: backfill

#6985 feat: add profile_dau_metrics_marketing_geo_testing_v1 for firefox_ios and fenix
  sql/moz-fx-data-shared-prod/fenix/profile_dau_metrics_marketing_geo_testing/view.sql
  sql/moz-fx-data-shared-prod/fenix_derived/profile_dau_metrics_marketing_geo_testing_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/fenix_derived/profile_dau_metrics_marketing_geo_testing_v1/query.sql
  sql/moz-fx-data-shared-prod/fenix_derived/profile_dau_metrics_marketing_geo_testing_v1/schema.yaml
  sql/moz-fx-data-shared-prod/firefox_ios/profile_dau_metrics_marketing_geo_testing/view.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/profile_dau_metrics_marketing_geo_testing_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/profile_dau_metrics_marketing_geo_testing_v1/query.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/profile_dau_metrics_marketing_geo_testing_v1/schema.yaml
Labels: enhancement

#6998 feat(DENG-7842): add backfill entry for profile_dau_metrics_marketing_geo_testing_v1 (fenix and ios)
  sql/moz-fx-data-shared-prod/fenix_derived/profile_dau_metrics_marketing_geo_testing_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/profile_dau_metrics_marketing_geo_testing_v1/backfill.yaml
Labels: backfill

#7023 feat: add bqetl_format pre-commit
  .pre-commit-config.yaml
Labels: enhancement

#7032 feat: handle cases when SQL syntaxt is invalid and add invalid to the final report
  bigquery_etl/format_sql/format.py
  tests/cli/test_cli_format.py
Labels: enhancement

#6858 feat: add usage_reporting generator
  bqetl_project.yaml
  sql_generators/usage_reporting/README.md
  sql_generators/usage_reporting/__init__.py
  sql_generators/usage_reporting/templates/app_union.view.sql.jinja
  sql_generators/usage_reporting/templates/channel.view.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.query.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.schema.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.query.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.schema.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.query.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.schema.yaml.jinja
Labels: enhancement

#7047 fix: make sure firefox_desktop app_id is set correctly in the union view
  sql_generators/usage_reporting/templates/app_union.view.sql.jinja
Labels: bug

#7048 feat: apply retention on usage_reporting_clients daily and last_seen
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.metadata.yaml.jinja
Labels: metadata

#7077 feat: add windows_build_number to usage_reporting_clients_daily template
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.query.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.schema.yaml.jinja
Labels: enhancement

#7091 feat: move udf calls for getting values based on os fields into views
  sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates/view.sql
  sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/query.sql
  sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/schema.yaml
Labels: enhancement

#7088 feat: Add baseline_active_users_aggregates_v1 backfill
  sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/backfill.yaml
Labels: backfill

#7099 feat: add desktop_dau_distribution_id_history_v1 as one of the sources for distribution_id to baseline_active_users
  sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
Labels: enhancement

#7100 feat: add backfill entry for firefox_desktop_derived.baseline_active_users_aggregates_v1
  sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/backfill.yaml
Labels: backfill

#7109 feat: add beta channels to fenix and firefox_ios usage_reporting configuration
  bqetl_project.yaml
Labels: enhancement

#7102 DENG-7860 - complete managed backfill for firefox_desktop_derived.baseline_active_users_aggregates_v1
  sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/backfill.yaml
Labels: backfill

#7110 feat: add and rename some fields to make them more consistent with baseline_active_users for consistency
  sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
Labels: enhancement

#7089 feat: add dt to partnership mapping and default to null
  sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates/view.sql
Labels: enhancement
