Repository mozilla/bigquery-etl, pull requests merged in 2025-03, with the labels that each got.

#7050 feat: mark old retention related datasets as deprecated
  sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/checks.sql
  sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/checks.sql
  sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/checks.sql
  sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/checks.sql
  sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_2_v1/checks.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_2_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_4_v1/checks.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_4_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/checks.sql
  sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v1/metadata.yaml
  sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v2/metadata.yaml
Labels: deprecation

#7129 feat(): add release channel to usage_reporting fenix and ios configuration
  bqetl_project.yaml
Labels: enhancement

#7130 feat: add usage_reporting_active_users_aggregates templates
  sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates/view.sql
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.query.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.schema.yaml.jinja
Labels: enhancement

#7072 feat(): add composite active users to usage reporting generator
  sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
  sql_generators/mobile_kpi_support_metrics/templates/active_users.view.sql
  sql_generators/usage_reporting/__init__.py
  sql_generators/usage_reporting/templates/composite_active_users.view.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
Labels: enhancement

#7145 feat(DENG-7865): make sure the usage_reporting_active_users_aggregates templates are rendered and writen to file
  sql_generators/usage_reporting/__init__.py
  sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.query.sql.jinja
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.schema.yaml.jinja
Labels: enhancement

#7146 feat(DENG-7984): add focus_android and focus_ios to usage_reporting generator configuration
  bqetl_project.yaml
Labels: enhancement

#7204 feat: add a new bqetl_usage_reporting DAG and schedule usage_reporting related queries in it.
  dags.yaml
  sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.metadata.yaml.jinja
  sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.metadata.yaml.jinja
Labels: enhancement

#7207 feat: move usage_reporting logic into a separate module outside of the __init__
  sql_generators/usage_reporting/__init__.py
  sql_generators/usage_reporting/usage_reporting.py
Labels: enhancement

#7194 feat(DENG-8074): Add testing to usage reporting generator (part 1)
  sql_generators/usage_reporting/__init__.py
  sql_generators/usage_reporting/usage_reporting.py
  tests/sql_generators/usage_reporting/test_usage_reporting.py
Labels: enhancement

#7210 feat: Disable monitoring (Bigeye metrics) for focus_ios, klar_ios, focus_android, and klar_android (telemetry changes).
  bqetl_project.yaml
Labels: deprecation

#7218 Run test backfill of newtab_interactions_hourly_v1
  sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/backfill.yaml
Labels: backfill

#7209 feat: add backfill entry for usage_reporting clients daily focus android and ios
  sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/usage_reporting_clients_daily_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/org_mozilla_focus_derived/usage_reporting_clients_daily_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/usage_reporting_clients_daily_v1/backfill.yaml
  sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/usage_reporting_clients_daily_v1/backfill.yaml
Labels: backfill

#7224 feat: add more apps to glean generation bigconfig skip apps
  bqetl_project.yaml
Labels: data checks
